name: Update ICS file

on:
  schedule:
    - cron: '0 2 * * *'   # runs daily at 02:00 UTC
  workflow_dispatch:      # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # no extra deps required; all stdlib

      - name: Run merge script
        run: python merge_ics.py

      - name: Commit combined.ics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          if git status --porcelain | grep -q "combined.ics"; then
            git add combined.ics
            git commit -m "Update combined.ics (auto)"
            git push
          else
            echo "No changes to combined.ics"
          fi
